TiendaMusica.Web/TiendaMusica.Web/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using TiendaMusica.Infraestructura;
using TiendaMusica.Logica;
using TiendaMusica.Logica.ViewModels;
using TiendaMusica.Web.Utilidades;

namespace TiendaMusica.Web.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly TiendaConsultas tienda;
        public AlbumsController()
        {
            tienda = ConstructorServicios.TiendaConsultas();
        }
        public ActionResult Edit(string artista, string album)
        {
            AlbumEditarViewModel model = tienda.EditarAlbum(album);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(string artista, string album, HttpPostedFileBase archivo, AlbumEditarViewModel model)
        {
            if (archivo != null)
            {
                if ((archivo.ContentType).Contains("image"))
                {
                    string nombreArchivo = archivo.FileName.ObtenerMD5() + Path.GetExtension(archivo.FileName);
                    GrabarImagen(archivo, nombreArchivo);
                    model.Imagen = nombreArchivo;
                }
            }

            if (ModelState.IsValid)
            {
                tienda.ActualizarAlbum(album, model);
                return Redirect(string.Format("/{0}/albums", artista));
            }
            else
            {
                return View(model);
            }

        } 
        private void GrabarImagen(HttpPostedFileBase archivo, string nombreArchivo)
        {
            MemoryStream ms = new MemoryStream();
            archivo.InputStream.CopyTo(ms);
            Imagen imagen = new Imagen(ms, archivo.FileName, archivo.ContentType, Server.MapPath("~/Albums"));
            imagen.Grabar(nombreArchivo, Server.MapPath("~/Albums/Thumbnails"));

        }

        public ActionResult Tracks(string artista, string album) {

            IEnumerable<CancionesPorAlbumViewModel> canciones =  tienda.Canciones(album);
            return View(canciones);
        }
    }
}

TiendaMusica.Web/TiendaMusica.Web/Controllers/ArtistasController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TiendaMusica.Infraestructura;
using TiendaMusica.Logica;
using TiendaMusica.Logica.ViewModels;

namespace TiendaMusica.Web.Controllers
{
    public class ArtistasController : Controller
    {
        private readonly TiendaConsultas tienda;
        public ArtistasController()
        {
            tienda = ConstructorServicios.TiendaConsultas();
        }
        public ActionResult Albums(string artista)
        {
            /// viene el codigo
            /// Logica de Negocio no va en un controlador
            /// 
            IEnumerable<AlbumsPorArtistaViewModel> albums =
                                                        tienda.Albums(artista);

            return View(albums);
        }

        public ActionResult List() {

            IEnumerable<ArtistasViewModel> artistas = tienda.Artistas();
            return View(artistas);
        }
    }
}

TiendaMusica.Web/TiendaMusica.Web/Controllers/CancionesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TiendaMusica.Infraestructura;
using TiendaMusica.Logica;
using TiendaMusica.Logica.ViewModels;
using TiendaMusica.Web.Utilidades;

namespace TiendaMusica.Web.Controllers
{
    public class CancionesController : Controller
    {

        private readonly TiendaConsultas tienda;
        public CancionesController()
        {
            tienda = ConstructorServicios.TiendaConsultas();
        }

        public ActionResult Edit(string artista, string album, string cancion)
        {
            CancionEditarViewModel model = tienda.EditarCancion(cancion);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(string artista, string album, string cancion, HttpPostedFileBase archivo, CancionEditarViewModel model)
        {

            if (archivo != null)
            {
                if ((archivo.ContentType).Contains("audio"))
                {
                    string nombreArchivo = archivo.FileName.ObtenerMD5() + Path.GetExtension(archivo.FileName);
                    GrabarAudio(archivo, nombreArchivo);
                    model.FilePath = nombreArchivo;
                }
            }

            if (ModelState.IsValid)
            {
                tienda.ActualizarCancion(cancion, model);
                return Redirect(string.Format("/{0}/{1}/tracks", artista, album));
            }
            else
            {
                return View(model);
            }

        }

        private void GrabarAudio(HttpPostedFileBase archivo, string nombreArchivo)
        {
            MemoryStream ms = new MemoryStream();
            archivo.InputStream.CopyTo(ms);
            Audio audio = new Audio(ms, archivo.FileName, archivo.ContentType, Server.MapPath("~/Tracks"));
            audio.Grabar(nombreArchivo);
        }


    }
}

TiendaMusica.Web/TiendaMusica.Web/Controllers/DownloadController.cs
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaMusica.Logica;

namespace TiendaMusica.Web.Controllers
{
    public class DownloadController : Controller
    {
        // GET: Download
        public ActionResult Reporte(string id)
        {

            string[] fileEntries = Directory.GetFiles(Server.MapPath("~/Downloads"), "*." + id);
            foreach (var item in fileEntries)
            {
                FilePathResult download = new FilePathResult(item, MimeMapping.GetMimeMapping(fileEntries[0]));
                download.FileDownloadName = Path.GetFileName(item);
                return download;
            }
              
            return Redirect("~/Error/Error404");

        }

        public ActionResult Excel()
        {

            FileStreamResult download = new FileStreamResult(ReporteSimple.Excel(), "application/vnd.ms-excel");
            download.FileDownloadName = "Excel.xls";

            return download;

        }
    }
}

TiendaMusica.Web/TiendaMusica.Web/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TiendaMusica.Web.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Error404()
        {
            return View();
        }
    }
}

TiendaMusica.Web/TiendaMusica.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TiendaMusica.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TiendaMusica.Web/TiendaMusica.Web/Views/Albums/Edit.cshtml
@model TiendaMusica.Logica.ViewModels.AlbumEditarViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "Albums", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Seleccione un archivo</label>
            <div class="col-md-10">
                <input type="file" id="archivo" name="archivo" class="form-control" accept="image/*" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/Albums/Thumbnails/@Model.Imagen"  id="thumbnail"  style="width:200px" class="img img-thumbnail" />
                <input type="hidden" name="Imagen" value="@Model.Imagen" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>

    </div>
    }

    <div>
      <a href="/@Model.ArtistaSlug/albums" class="btn btn-default">Cancelar</a>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script>

         
        $("#archivo").change(function () {
            var file = (this).files[0];

            if (file.size > 20480000) {
                $("#archivo").val("");
                alert("El arvhivo supera los 20Mb");
                return;
            }

            if ((this).files && file) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#thumbnail').attr('src', e.target.result);
                }
                reader.readAsDataURL(file);
            }

        });

    </script>

TiendaMusica.Web/TiendaMusica.Web/Views/Albums/Tracks.cshtml
@model IEnumerable<TiendaMusica.Logica.ViewModels.CancionesPorAlbumViewModel>

@{
    ViewBag.Title = "Tracks";
}


<h2>Tracks</h2>

<hr />

<div class="row">
    <div class="col-md-8">


        <table id="track-list" class="table table-bordered">
            <thead>
                <tr>
                    <th colspan="4" class="text-center">
                        <audio id="audio" controls>
                            <source  type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                    </th>
                </tr>

                <tr>
                    <th></th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cancion)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Tamano)
                    </th>
                    <th></th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @if (item.FilePath != null)
                        {
                            <a href="#" data-file="@item.FilePath" class="play">
                                <span class="glyphicon glyphicon-play-circle"></span>
                            </a>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cancion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tamano) b
                    </td>
                    <td>
                        <a href="/admin/@item.ArtistaSlug/@item.AlbumSlug/@item.CancionSlug/edit">Editar</a>
                    </td>
                </tr>
            }

        </table>


    </div>

</div>

<div>
    <a href="/@Model.First().ArtistaSlug/albums" class="btn btn-default">Albums</a>
</div>



@Scripts.Render("~/bundles/jquery")
<script>

    $("#track-list").on("click", ".play", function (e) {

        e.preventDefault();
        var file = $(this).data("file");
        $("#audio").attr("src", "/Tracks/" + file).trigger("play");

    })

</script>

TiendaMusica.Web/TiendaMusica.Web/Views/Artistas/Albums.cshtml
@model IEnumerable<TiendaMusica.Logica.ViewModels.AlbumsPorArtistaViewModel>

@{
    ViewBag.Title = "Albums";
}

<h2>Albums</h2>
 
<hr />

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-md-3 portfolio-item">
            <a href="/@item.ArtistaSlug/@item.AlbumSlug/tracks">
                <img src="~/Albums/Thumbnails/@item.ImagenPath" class="img img-thumbnail" style="height:200px; " />
            </a>
            <h3>
                <a href="/@item.ArtistaSlug/@item.AlbumSlug/tracks">@item.Album </a>
            </h3>
            <p><a href="/admin/@item.ArtistaSlug/@item.AlbumSlug/edit">Editar</a></p>
        </div>
    }

</div>


<a href="/artists" class="btn btn-default ">Artistas</a>

TiendaMusica.Web/TiendaMusica.Web/Views/Artistas/List.cshtml
@model IEnumerable<TiendaMusica.Logica.ViewModels.ArtistasViewModel>

@{
    ViewBag.Title = "Artistas";
}

<h2>Artistas</h2>

<div class="row">
    <div class="col-md-6">
        <ul class="list-group">
            @foreach (var item in Model)
            {
                <li class="list-group-item">
                    <a href="@item.Slug/albums">@item.Artista</a>
                </li>
            }
        </ul>
    </div>
</div>

TiendaMusica.Web/TiendaMusica.Web/Views/Canciones/Edit.cshtml
@model TiendaMusica.Logica.ViewModels.CancionEditarViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm("Edit", "Canciones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Canción</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Audio (mp3 | max 20Mb)</label>
            <div class="col-md-10">
                <input type="file" id="archivo" name="archivo" class="form-control" accept="audio/mp3" />
                <input type="hidden" name="FilePath" value="@Model.FilePath" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <audio id="audio" controls>
                    @if (Model.FilePath != null)
                    {
                        <source src="~/Tracks/@Model.FilePath" type="audio/mpeg">
                    }
                    else {
                        <source type="audio/mpeg">
                    }
                    Your browser does not support the audio element.
                </audio>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tamano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tamano, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/@Model.ArtistaSlug/@Model.AlbumSlug/tracks" class="btn btn-default">Cancelar</a>
</div>

@Scripts.Render("~/bundles/jquery")
<script>

    $("#archivo").change(function () {

        var file = (this).files[0];
        $("#Tamano").val(file.size);

        if (file.size > 20480000) {
            $("#archivo").val("");
            alert("El arvhivo supera los 20Mb");
            return;
        }

        if ((this).files && file) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#audio').attr('src', e.target.result);
            }
            reader.readAsDataURL(file);
        }
    });

</script>

TiendaMusica.Web/TiendaMusica.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TiendaMusica.Web/TiendaMusica.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TiendaMusica.Web/TiendaMusica.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TiendaMusica.Web/TiendaMusica.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li><a href="/artists">Artistas</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>